### ISSUE TITLE
数据预计开源时间

### ISSUE THREAD

**Issue by yy524** [SpeechColab/GigaSpeech2#1]
您好：
       请问数据预计什么时间开源呢？

**Comment by yfyeung** [comment]
您好，一会就开源，目前数据传完了，在测试下载。

**Comment by yfyeung** [comment]
See https://huggingface.co/datasets/speechcolab/gigaspeech2

**Comment by yy524** [comment]
@yfyeung , 谢谢数据开源，我这边用whisper识别泰语，发现经常会识别出多余单词，请问您是怎么解决这个问题的呢？

**Comment by yy524** [comment]
@yfyeung 谢谢~

**Comment by yy524** [comment]
@yfyeung ，您好，请问论文中使用gigaspeech2训练的泰语ASR模型，会开源吗？

**Comment by yfyeung** [comment]
> @yfyeung 谢谢~

See https://github.com/SpeechColab/GigaSpeech2/issues/2
