### ISSUE TITLE
load_dataset bug

### ISSUE THREAD

**Issue by ruby11dog** [SpeechColab/GigaSpeech2#3]
when i run "dataset = load_dataset("speechcolab/gigaspeech2", split='data.th')" The program was interrupted by：
Traceback (most recent call last):
File "/root/miniforge3/envs/audio_process/lib/python3.8/site-packages/datasets/builder.py", line 1894, in _prepare_split_single
writer.write_table(table)
File "/root/miniforge3/envs/audio_process/lib/python3.8/site-packages/datasets/arrow_writer.py", line 570, in write_table
pa_table = table_cast(pa_table, self._schema)
File "/root/miniforge3/envs/audio_process/lib/python3.8/site-packages/datasets/table.py", line 2324, in table_cast
return cast_table_to_schema(table, schema)
File "/root/miniforge3/envs/audio_process/lib/python3.8/site-packages/datasets/table.py", line 2282, in cast_table_to_schema
raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast

**Comment by yfyeung** [comment]
If you want to download some specify files, you can use:
```python
from datasets import load_dataset

train_ds = load_dataset("speechcolab/gigaspeech2", data_files={"train": "data/th/train/*.tar.gz"}, split="train")
train_raw_ds = load_dataset("speechcolab/gigaspeech2", data_files={"train_raw": "data/th/train_raw.tsv"}, split="train_raw")
train_refined_ds = load_dataset("speechcolab/gigaspeech2", data_files={"train_refined": "data/th/train_refined.tsv"}, split="train_refined")
dev_ds = load_dataset("speechcolab/gigaspeech2", data_files={"dev": "data/th/dev.tar.gz"}, split="dev")
dev_meta_ds = load_dataset("speechcolab/gigaspeech2", data_files={"dev_meta": "data/th/dev.tsv"}, split="dev_meta")
test_ds = load_dataset("speechcolab/gigaspeech2", data_files={"test": "data/th/test.tar.gz"}, split="test")
test_meta_ds = load_dataset("speechcolab/gigaspeech2", data_files={"test_meta": "data/th/test.tsv"}, split="test_meta")

print("Train dataset:", train_ds)
print("Train raw dataset:", train_raw_ds)
print("Train refined dataset:", train_refined_ds)
print("Dev dataset:", dev_ds)
print("Dev meta dataset:", dev_meta_ds)
print("Test dataset:", test_ds)
print("Test meta dataset:", test_meta_ds)

```

**Comment by yfyeung** [comment]
I have requested assistance from the HuggingFace team to help create a script `gigaspeech2.py` that supports this.

**Comment by yfyeung** [comment]
Hi, @ruby11dog

The addition of the script `gigaspeech2.py` to Hugging Face is currently disabled. We do not support this functionality as our dataset was not uploaded through `datasets`.

To download the Thai subset, you can use the following commands:
```shell
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/datasets/speechcolab/gigaspeech2
git lfs pull --include "data/th"
```
