### ISSUE TITLE
越南语和印尼语的模型会开源麽

### ISSUE THREAD

**Issue by zhusy09** [SpeechColab/GigaSpeech2#6]

**Comment by yfyeung** [comment]
会的

**Comment by yfyeung** [comment]
您好，越南语的模型可在 huggingface 下载 https://huggingface.co/zzasdf/icefall-asr-gigaspeech2-vi-zipformer

**Comment by zhusy09** [comment]
谢谢

**Comment by yfyeung** [comment]
@zhusy09 您好，欢迎尝试我们最新的 7 万小时训练的越南语模型，https://huggingface.co/zzasdf/viet_iter3_pseudo_label/tree/main/exp

**Comment by herbiel** [comment]
有印尼语模型吗
