### ISSUE TITLE
Release the original transcript?

### ISSUE THREAD

**Issue by XqFeng-Josie** [SpeechColab/GigaSpeech2#7]
I have noticed that all transcripts of audios are post-processed, so that all the texts are uppered. I want to know if you can release the original text with punction, that would be more helpful! thank you for your team contribution.

**Comment by yfyeung** [comment]
> I have noticed that all transcripts of audios are post-processed, so that all the texts are uppered. I want to know if you can release the original text with punction, that would be more helpful! thank you for your team contribution.

Thank you for your feedback. Unfortunately, the original text with punctuation and case was lost during the forced alignment process.
