### ISSUE TITLE
Dataset preparation in other language

### ISSUE THREAD

**Issue by Tortoise17** [SpeechColab/GigaSpeech2#8]
Giving the crawler other channels path, is it possible to generate dataset of my own in other language?

**Comment by yfyeung** [comment]
@Tortoise17 Of course.

You can follow https://github.com/SpeechColab/GigaSpeech2/blob/main/pipeline/crawler/README.md.

Make sure you assign the right language id.
For example, the `ISO 639-1 language code` of `Thai` is `th` and the `ISO 639-2 language code` of `Thai` is `tha`.

**Comment by Tortoise17** [comment]
Great, and the format than can be used for training audio LDM2 for like speech model? I guess.

**Comment by Tortoise17** [comment]
Just one question, considering reference estimate, how much time it took to generate a prepared dataset 30,000 hours and on which GPU you have prepared the dataset?

**Comment by yfyeung** [comment]
> Great, and the format than can be used for training audio LDM2 for like speech model? I guess.

@Tortoise17 Yes. The original file type is probably `.webm` and it will be converted into `.wav`.

**Comment by yfyeung** [comment]
> Just one question, considering reference estimate, how much time it took to generate a prepared dataset 30,000 hours and on which GPU you have prepared the dataset?

@Tortoise17 You can refer:
<img width="678" alt="截屏2024-09-08 18 42 30" src="https://github.com/user-attachments/assets/c0a5ce4c-6c27-4d4e-9e53-fb09c0ac1030">

We suggest using faster-whisper and multi-gpu to parallelize the transcription.
